version: '3.1'

services:
  xestor.db.auth:
    image: postgres
    container_name: xestor.db.auth
    restart: always
    ports:
      - 5433:5432    
    environment:
      - POSTGRES_USER=semog
      - POSTGRES_PASSWORD=Dr4inY0u
      - POSTGRES_DB=black_list
    volumes:
      - pgdata:/data
  # db_push:
  #   build: .
  #   container_name: db_push
  #   env_file:
  #     - .env
  #   command: npx prisma db push
  #   volumes:
  #     - .:/usr/xestor.user
  #   depends_on:
  #     - postgres

  # xestor.user:
  #   build: .
  #   container_name: xestor.user
  #   env_file:
  #     - .env
  #   command: npm run dev
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   volumes:
  #     - .:/usr/xestor.user
  #   depends_on:
  #     - postgres
  #     - db_push

volumes:
  pgdata:
    driver: local
